name: MageOS Semantic Checker
run-name: ${{ github.actor }} is checking the semantic version
on: [pull_request]
jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Environment Debugging Output
        run: |
          echo "Event_path: ${GITHUB_EVENT_PATH}"
          echo 'Event: ${{ toJSON(github.event.pull_request) }}'
      # TODO: Add pull request labels
      # - name: Clean up labels
      #   uses: andymckay/labeler@master
      #   with:
      #     remove-labels: "svc"
      - name: Check out Semamtic Version Checker tool
        uses: actions/checkout@v3
        with:
          repository: mage-os/mirror-magento-semver
          path: magento-semver
      - name: Check out base branch - ${{ github.base_ref }}
        uses: actions/checkout@v3
        with:
          path: base-branch
          ref: ${{ github.base_ref }}
      - name: Check out new changes - ${{ github.event.pull_request.head.repo.full_name }} / ${{ github.head_ref }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: this-change
          ref: ${{ github.head_ref }}
      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          command: help
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cd magento-semver &&
          echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Install Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Semamtic Version Checker
        run: cd magento-semver && composer install
      - name: Run Semantic Version Checker (SVC)
        run: magento-semver/bin/svc compare base-branch this-change
      - name: Upload SVC output file
        uses: actions/upload-artifact@v3
        with:
          name: svc-log-file
          path: svc.log
      # TODO: Add pull request labels
      # - name: Add labels
      #   uses: andymckay/labeler@master
      #   with:
      #     add-labels: "svc"

